// <auto-generated />
using System;
using BarberShopAgenda.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShopAgenda.Infrastructure.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20260816162929_AddContaCliente")]
    partial class AddContaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoConfirmacao")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataHora");

                    b.HasIndex("ServicoId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("DiasTrabalho")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<TimeOnly?>("HorarioFimManha")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly?>("HorarioFimTarde")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly?>("HorarioInicioManha")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly?>("HorarioInicioTarde")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Barbeiros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DiasTrabalho = (byte)63,
                            Especialidade = "Cortes clássicos",
                            HorarioFimManha = new TimeOnly(12, 0, 0),
                            HorarioFimTarde = new TimeOnly(19, 0, 0),
                            HorarioInicioManha = new TimeOnly(9, 0, 0),
                            HorarioInicioTarde = new TimeOnly(13, 0, 0),
                            Nome = "Carlos Silva",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DiasTrabalho = (byte)63,
                            Especialidade = "Barba e navalha",
                            HorarioFimManha = new TimeOnly(12, 0, 0),
                            HorarioFimTarde = new TimeOnly(19, 0, 0),
                            HorarioInicioManha = new TimeOnly(9, 0, 0),
                            HorarioInicioTarde = new TimeOnly(13, 0, 0),
                            Nome = "João Pereira",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DiasTrabalho = (byte)63,
                            Especialidade = "Cortes modernos e degradê",
                            HorarioFimManha = new TimeOnly(12, 0, 0),
                            HorarioFimTarde = new TimeOnly(19, 0, 0),
                            HorarioInicioManha = new TimeOnly(9, 0, 0),
                            HorarioInicioTarde = new TimeOnly(13, 0, 0),
                            Nome = "Marcos Souza",
                            UsuarioId = 4
                        });
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Corte tradicional masculino",
                            DuracaoMinutos = 30,
                            Nome = "Corte de Cabelo",
                            Preco = 40.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aparar e desenhar barba",
                            DuracaoMinutos = 20,
                            Nome = "Barba",
                            Preco = 30.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Combo corte de cabelo e barba",
                            DuracaoMinutos = 50,
                            Nome = "Corte + Barba",
                            Preco = 60.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Design de sobrancelha na navalha",
                            DuracaoMinutos = 15,
                            Nome = "Sobrancelha",
                            Preco = 15.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Pigmentação para uniformizar a barba",
                            DuracaoMinutos = 40,
                            Nome = "Pigmentação de Barba",
                            Preco = 45.00m
                        });
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TokenResetSenha")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenResetSenhaExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenVerificacaoEmail")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenVerificacaoExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@barbershop.com",
                            EmailConfirmado = false,
                            Nome = "Administrador",
                            Papel = 0,
                            SenhaHash = "AQAAAAIAAYagAAAAEALS4Lb5vWiYPmmQFgUKKs5kmYjZALMI7i4meu9fPlAxq15d8thqwG9Ns75FRbzA4g=="
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos.silva@barbershop.com",
                            EmailConfirmado = false,
                            Nome = "Carlos Silva",
                            Papel = 1,
                            SenhaHash = "AQAAAAIAAYagAAAAEB/8Wz4FFhsxpPNegqz3iqcE1lO4G46znRK6GQ7gGZY0J2WdKaeuHZlGUgu4GhLMTQ=="
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "joao.pereira@barbershop.com",
                            EmailConfirmado = false,
                            Nome = "João Pereira",
                            Papel = 1,
                            SenhaHash = "AQAAAAIAAYagAAAAEBy7KwJ9F4W7DZzBXQle0B0NrCquufmoJIbVSNJ30VQBaMVTzhYjtGkHZ05KR1r19w=="
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marcos.souza@barbershop.com",
                            EmailConfirmado = false,
                            Nome = "Marcos Souza",
                            Papel = 1,
                            SenhaHash = "AQAAAAIAAYagAAAAEFeTriNcRDe10YZZpLPfi+s+UfCm1EwRMEbHlX355or+Y+IESPd6txvMMI7ajmtkqQ=="
                        });
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("BarberShopAgenda.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberShopAgenda.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberShopAgenda.Domain.Entities.Servico", "Servico")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Barbeiro", b =>
                {
                    b.HasOne("BarberShopAgenda.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Barbeiro")
                        .HasForeignKey("BarberShopAgenda.Domain.Entities.Barbeiro", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("BarberShopAgenda.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("BarberShopAgenda.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
