// <auto-generated />
using System;
using BarberShopAgenda.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberShopAgenda.Infrastructure.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20260815194434_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataHora");

                    b.HasIndex("ServicoId");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Barbeiros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Especialidade = "Cortes clássicos",
                            Nome = "Carlos Silva"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Especialidade = "Barba e navalha",
                            Nome = "João Pereira"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Especialidade = "Cortes modernos e degradê",
                            Nome = "Marcos Souza"
                        });
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Corte tradicional masculino",
                            DuracaoMinutos = 30,
                            Nome = "Corte de Cabelo",
                            Preco = 40.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aparar e desenhar barba",
                            DuracaoMinutos = 20,
                            Nome = "Barba",
                            Preco = 30.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Combo corte de cabelo e barba",
                            DuracaoMinutos = 50,
                            Nome = "Corte + Barba",
                            Preco = 60.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Design de sobrancelha na navalha",
                            DuracaoMinutos = 15,
                            Nome = "Sobrancelha",
                            Preco = 15.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Pigmentação para uniformizar a barba",
                            DuracaoMinutos = 40,
                            Nome = "Pigmentação de Barba",
                            Preco = 45.00m
                        });
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("BarberShopAgenda.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberShopAgenda.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberShopAgenda.Domain.Entities.Servico", "Servico")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("BarberShopAgenda.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
